// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/repository/URLKeeper.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockURLKeeper is a mock of URLKeeper interface.
type MockURLKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockURLKeeperMockRecorder
}

// MockURLKeeperMockRecorder is the mock recorder for MockURLKeeper.
type MockURLKeeperMockRecorder struct {
	mock *MockURLKeeper
}

// NewMockURLKeeper creates a new mock instance.
func NewMockURLKeeper(ctrl *gomock.Controller) *MockURLKeeper {
	mock := &MockURLKeeper{ctrl: ctrl}
	mock.recorder = &MockURLKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLKeeper) EXPECT() *MockURLKeeperMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockURLKeeper) FindByID(id string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockURLKeeperMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockURLKeeper)(nil).FindByID), id)
}

// FindByLink mocks base method.
func (m *MockURLKeeper) FindByLink(link string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByLink", link)
	ret0, _ := ret[0].(string)
	return ret0
}

// FindByLink indicates an expected call of FindByLink.
func (mr *MockURLKeeperMockRecorder) FindByLink(link interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByLink", reflect.TypeOf((*MockURLKeeper)(nil).FindByLink), link)
}

// GetNumberOfEntries mocks base method.
func (m *MockURLKeeper) GetNumberOfEntries() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNumberOfEntries")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetNumberOfEntries indicates an expected call of GetNumberOfEntries.
func (mr *MockURLKeeperMockRecorder) GetNumberOfEntries() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNumberOfEntries", reflect.TypeOf((*MockURLKeeper)(nil).GetNumberOfEntries))
}

// PingDBConnect mocks base method.
func (m *MockURLKeeper) PingDBConnect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingDBConnect")
	ret0, _ := ret[0].(error)
	return ret0
}

// PingDBConnect indicates an expected call of PingDBConnect.
func (mr *MockURLKeeperMockRecorder) PingDBConnect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingDBConnect", reflect.TypeOf((*MockURLKeeper)(nil).PingDBConnect))
}

// SetShortURL mocks base method.
func (m *MockURLKeeper) SetShortURL(encodedString, url string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetShortURL", encodedString, url)
	ret0, _ := ret[0].(string)
	return ret0
}

// SetShortURL indicates an expected call of SetShortURL.
func (mr *MockURLKeeperMockRecorder) SetShortURL(encodedString, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetShortURL", reflect.TypeOf((*MockURLKeeper)(nil).SetShortURL), encodedString, url)
}
