// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/url_keeper.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/0loff/go_link_shortener/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockURLKeeper is a mock of URLKeeper interface.
type MockURLKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockURLKeeperMockRecorder
}

// MockURLKeeperMockRecorder is the mock recorder for MockURLKeeper.
type MockURLKeeperMockRecorder struct {
	mock *MockURLKeeper
}

// NewMockURLKeeper creates a new mock instance.
func NewMockURLKeeper(ctrl *gomock.Controller) *MockURLKeeper {
	mock := &MockURLKeeper{ctrl: ctrl}
	mock.recorder = &MockURLKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLKeeper) EXPECT() *MockURLKeeperMockRecorder {
	return m.recorder
}

// BatchInsertShortURLS mocks base method.
func (m *MockURLKeeper) BatchInsertShortURLS(ctx context.Context, uid string, entries []models.URLEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchInsertShortURLS", ctx, uid, entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchInsertShortURLS indicates an expected call of BatchInsertShortURLS.
func (mr *MockURLKeeperMockRecorder) BatchInsertShortURLS(ctx, uid, entries interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsertShortURLS", reflect.TypeOf((*MockURLKeeper)(nil).BatchInsertShortURLS), ctx, uid, entries)
}

// FindByID mocks base method.
func (m *MockURLKeeper) FindByID(ctx context.Context, id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockURLKeeperMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockURLKeeper)(nil).FindByID), ctx, id)
}

// FindByLink mocks base method.
func (m *MockURLKeeper) FindByLink(ctx context.Context, link string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByLink", ctx, link)
	ret0, _ := ret[0].(string)
	return ret0
}

// FindByLink indicates an expected call of FindByLink.
func (mr *MockURLKeeperMockRecorder) FindByLink(ctx, link interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByLink", reflect.TypeOf((*MockURLKeeper)(nil).FindByLink), ctx, link)
}

// FindByUser mocks base method.
func (m *MockURLKeeper) FindByUser(ctx context.Context, uid string) []models.URLEntry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUser", ctx, uid)
	ret0, _ := ret[0].([]models.URLEntry)
	return ret0
}

// FindByUser indicates an expected call of FindByUser.
func (mr *MockURLKeeperMockRecorder) FindByUser(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUser", reflect.TypeOf((*MockURLKeeper)(nil).FindByUser), ctx, uid)
}

// GetMetrics mocks base method.
func (m *MockURLKeeper) GetMetrics() models.Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrics")
	ret0, _ := ret[0].(models.Metrics)
	return ret0
}

// GetMetrics indicates an expected call of GetMetrics.
func (mr *MockURLKeeperMockRecorder) GetMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrics", reflect.TypeOf((*MockURLKeeper)(nil).GetMetrics))
}

// GetNumberOfEntries mocks base method.
func (m *MockURLKeeper) GetNumberOfEntries(ctx context.Context) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNumberOfEntries", ctx)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetNumberOfEntries indicates an expected call of GetNumberOfEntries.
func (mr *MockURLKeeperMockRecorder) GetNumberOfEntries(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNumberOfEntries", reflect.TypeOf((*MockURLKeeper)(nil).GetNumberOfEntries), ctx)
}

// PingConnect mocks base method.
func (m *MockURLKeeper) PingConnect(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingConnect", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// PingConnect indicates an expected call of PingConnect.
func (mr *MockURLKeeperMockRecorder) PingConnect(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingConnect", reflect.TypeOf((*MockURLKeeper)(nil).PingConnect), ctx)
}

// SetDelShortURLS mocks base method.
func (m *MockURLKeeper) SetDelShortURLS(URLSList []models.DelURLEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDelShortURLS", URLSList)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDelShortURLS indicates an expected call of SetDelShortURLS.
func (mr *MockURLKeeperMockRecorder) SetDelShortURLS(URLSList interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDelShortURLS", reflect.TypeOf((*MockURLKeeper)(nil).SetDelShortURLS), URLSList)
}

// SetShortURL mocks base method.
func (m *MockURLKeeper) SetShortURL(ctx context.Context, uid, token, url string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetShortURL", ctx, uid, token, url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetShortURL indicates an expected call of SetShortURL.
func (mr *MockURLKeeperMockRecorder) SetShortURL(ctx, uid, token, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetShortURL", reflect.TypeOf((*MockURLKeeper)(nil).SetShortURL), ctx, uid, token, url)
}
